prometheus:
  spring-boot: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\spring-boot.json
  node-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\node-exporter.json
  nginx-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  caddy: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  traefik: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\traefik
traefik:
  path: /home/my-traefik/config
build:
  image: /home/devops/image
  helm: /home/helm-repo
etcd:
  endpoints: http://server.gpg123.vip:12379
repo:
  helm:
    name: gpg_dev
    url: https://helm-repo.gpg123.vip/index.yaml
  docker:
    - name: aliyun
      url:
basePath: /home
#git应用
git:
  #gitee仓库
  gitee:
    username: gpg-dev_admin
    access_token: d325b8ea7d9ecb538909fab590b204b8
    grant_type: authorization_code
    redirect_uri: https://gpg123.cn/git/gitee
    client_id: 4205d9756e46effb45c437308d808f7b551414563cbec9f5aa0ec9402e0753d6
    client_secret: 3774068556c18b1e70400229c45530a1385dad8189612dc1dfaf7a5b06a84c04
    api: https://gitee.com/oauth/token
  github:
    username: 2694484453
    access_token: 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
#链路追踪
otel:
  service:
    name: ${spring.application.name}-${os.name}
  exporter:
    otlp:
      endpoint: http://124.221.2.29:4318
      timeout: 10s
# 大模型
ai:
  tyqw:
    api-key: sk-37d9ef3dd4e74516b355f7ccba0f73cd
    http: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    sdk: https://dashscope.aliyuncs.com/compatible-mode/v1

# 链路追踪
trace:
  api: http://ecs.gpg123.vip:16686/api
#监控
monitor:
  prometheus:
    endpoint: https://prometheus.gpg123.vip
  alertmanager:
    endpoint: https://alertmanager.gpg123.vip
