traefik:
  path: /home/my-traefik/config
  api: https://traefik.ecs.gpg123.vip/api
caddy:
  api: http://hongkong.gpg123.vip:2020
build:
  image: /home/devops/image
  helm: /home/helm-repo
etcd:
  endpoints: http://server.gpg123.vip:12379
repo:
  helm:
    name: default
    url: https://dev-gpg.oss-cn-hangzhou.aliyuncs.com/helm-charts
  docker:
    - name: aliyun
      url:
basePath: /home
docker:
  address: tcp://hongkong.gpg123.vip:2345
  tls:
    enabled: false
    certPath: ""
#git应用
git:
  #gitee仓库
  gitee:
    api: https://gitee.com/oauth/token
  github:
    username: 2694484453
    access_token: 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
# 大模型
ai:
  tyqw:
    api-key: sk-37d9ef3dd4e74516b355f7ccba0f73cd
    http: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    sdk: https://dashscope.aliyuncs.com/compatible-mode/v1
  deepseek:
    api-key: sk-37d9ef3dd4e74516b355f7ccba0f73cd
    http: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

# 链路追踪
trace:
  api: http://ecs.gpg123.vip:16686/api
#监控
monitor:
  prometheus:
    exporterPath: "/home/prometheus/exporter"
    endpoint: https://prometheus.gpg123.vip
  alertmanager:
    endpoint: https://alertmanager.gpg123.vip
# ide
ide:
  path: /home/codespace
  url: https://code-server.gpg123.vip
#远程主机
remote:
  host: tcs.gpg123.vip
  port: 22
  userName: root
  passWord: 1999y4m30D%
#frp
frp:
  server:
    url: http://hongkong.gpg123.vip:7500
    ip: hongkong.gpg123.vip
    port: 7000
    token: ADt8zh5VFdJKcccVWh2jkv1l6Z0IblSvm0H7M2yclJpYkWV0KPEadr9gZWdd77HM
    userName: gaopuguang
    passWord: 1999y4m30d
#cloud
cloud:
  aliyun:
    accessKeyId: xx
    accessKeySecret: xx
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    ossDomain: https://dev-gpg.oss-cn-hangzhou.aliyuncs.com
    bucketName: dev-gpg
#访问分析
analytics:
  umami:
    api: https://cloud.umami.is/analytics/us/api
    share-id: iUX6Qz9BIwpXraRV
    website-id: bdf579c4-ccad-4f66-84ad-12125e206bc9
    token: TL89uSFeV06lMpJM6aHCftEGk6AvyrA6VTC9xQsN0Nxf6ryxQ/qQdas7M7J0SZRa5uu7fDrsQyxZPjvh1E2KRC6OwrHOZg43wg+mRE5m1sHGysbDavOY3TBjD35gXgZZU81C89hcrgtkuDVAH71i7nzp0B/FgqNN/1uwaSPyb3Fs1wjIUarSY8Wx1F1Q04mOTNJ4EFSSjr41tzXfC1CQuo4huJZsx16zXbcn8u4oFmVGwVdp08sNik/ZSfhEEQaZcDo19/eWn4ROQZjcJkvjVdDGqSA3T/EsoKycxkEhqh64czQxuEgUbJwlMJxX02a4X69xM1aGmwtT1yDPzLR3iqicklP/WUtJ/6DOpA==
