traefik:
  path: /home/my-traefik/config
build:
  image: /home/devops/image
  helm: /home/helm-repo
etcd:
  endpoints: http://server.gpg123.vip:12379
repo:
  helm:
    name: gpg_dev
    url: https://helm-repo.gpg123.vip
  docker:
    - name: aliyun
      url:
basePath: /home
#git应用
git:
  #gitee仓库
  gitee:
    api: https://gitee.com/oauth/token
  github:
    username: 2694484453
    access_token: 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
# 大模型
ai:
  tyqw:
    api-key: sk-37d9ef3dd4e74516b355f7ccba0f73cd
    http: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    sdk: https://dashscope.aliyuncs.com/compatible-mode/v1
  deepseek:
    api-key: sk-37d9ef3dd4e74516b355f7ccba0f73cd
    http: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

# 链路追踪
trace:
  api: http://ecs.gpg123.vip:16686/api
#监控
monitor:
  prometheus:
    endpoint: https://prometheus.gpg123.vip
  alertmanager:
    endpoint: https://alertmanager.gpg123.vip
# ide
ide:
  path: /home/ide
#远程主机
remote:
  host: tcs.gpg123.vip
  port: 22
  userName: root
  passWord: 1999y4m30D%
#frp
frp:
  server:
    protocol: http
    host: hcs.gpg123.vip
    port: 7500
    userName: gaopuguang
    passWord: 1999y4m30d