#链路追踪
otel:
  service:
    name: ${spring.application.name}
  logs:
    exporter: none
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://47.97.162.27:4318
      metrics:
        endpoint: http://47.97.162.27:8889
        protocol: http/protobuf
        timeout: 10000
      timeout: 10000 # 10秒超时
      protocol: http/protobuf

#
#opentracing:
#  jaeger:
#    enabled: true # 启用对接Jaeger（可以不配置，默认true）
#    enable128-bit-traces: true # 使用短TraceID（可以不配置）
#    udp-sender:
#      host: 47.97.162.27 # 配置Jaeger服务器地址
#      port: 4318
#    service-name: ${spring.application.name}
