#链路追踪
otel:
  service:
    name: ${spring.application.name}-${os.name}
  exporter:
    otlp:
      traces:
        protocol: http/protobuf
        endpoint: http://tracing-analysis-dc-hz.aliyuncs.com/adapt_fy40et0jbp@da5cc2ebef9f41f_fy40et0jbp@53df7ad2afe8301/api/otlp/traces
      timeout: 10s
#      logs:
#        protocol: http/protobuf
      metrics:
        protocol: http/protobuf
        endpoint: http://tracing-analysis-dc-hz.aliyuncs.com/adapt_fy40et0jbp@da5cc2ebef9f41f_fy40et0jbp@53df7ad2afe8301/api/otlp/metrics
