prometheus:
  spring-boot: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\spring-boot.json
  node-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\node-exporter.json
  nginx-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  caddy: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  traefik: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\traefik
traefik:
  path: D:\Project\server\my-traefik\config
