prometheus:
  spring-boot: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\spring-boot.json
  node-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\node-exporter.json
  nginx-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  caddy: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  traefik: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\traefik
traefik:
  path: /home/my-traefik/config
build:
  image: /home/build/image
  helm: /home/build/helm
etcd:
  endpoints: http://server.gpg123.vip:12379
basePath: /home
#git应用
git:
  #gitee仓库
  gitee:
    grant_type: authorization_code
    redirect_uri: https://gpg123.cn/git/gitee
    client_id: 4205d9756e46effb45c437308d808f7b551414563cbec9f5aa0ec9402e0753d6
    client_secret: 3774068556c18b1e70400229c45530a1385dad8189612dc1dfaf7a5b06a84c04
    api: https://gitee.com/oauth/token
