prometheus:
  spring-boot: /home/prometheus/spring-boot.json
  node-exporter: /home/prometheus/node-exporter.json
  nginx-exporter: /home/prometheus/nginx-exporter.json
  caddy: /home/prometheus/caddy.json
  traefik: /home/prometheus/traefik.json
traefik:
  path: /home/my-traefik/config
