prometheus:
  spring-boot: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\spring-boot.json
  node-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\node-exporter.json
  nginx-exporter: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  caddy: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\nginx-exporter.json
  traefik: D:\Project\my-server\ruoyi-admin\src\main\resources\monitor\traefik
traefik:
  path: D:\Project\server\my-traefik\config
helm:
  index: https://helm-repo.gpg123.vip/index.yaml
  repoName: gpg_dev
build:
  image: D:\Project\my-server\ruoyi-admin\src\main\resources\build\image
  helm: D:\Project\my-server\ruoyi-admin\src\main\resources\build\helm
