apiVersion: batch/v1
kind: Job
metadata:
  name: git-clone
  namespace: devops
spec:
  #backoffLimit: 1
  template:
    metadata:
      name: git-clone
    spec:
      initContainers:
        - name: git
          image: alpine/git:v2.49.1
          imagePullPolicy: IfNotPresent
          env:
            - name: GIT_NAME
              value: "cloud-server"
            - name: GIT_URL
              value: "https://codeup.aliyun.com/63b19ef08de0fe7a6554f8c1/cloud-platform/cloud-server.git"
            - name: GIT_BRANCH
              value: "master"
          command: [ "/bin/sh", "-c", "/git-clone.sh" ]
          volumeMounts:
            - mountPath: "/home"
              name: data
            - mountPath: "/root/.git-credentials"
              name: git
              subPath: .git-credentials
            - mountPath: "/root/.gitconfig"
              name: git
              subPath: .gitconfig
            - mountPath: "/git-clone.sh"
              name: shell
              subPath: git-clone.sh
      containers:
        - image: busybox
          name: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "cd /home/cloud-server && ls -l"
          volumeMounts:
            - mountPath: /home
              name: data
      volumes:
        - name: shell
          configMap:
            name: shell-cm
            items:
              - key: git-clone.sh
                path: "git-clone.sh"
            defaultMode: 0755
        - name: git
          configMap:
            name: git-cm
            items:
              - key: .git-credentials
                path: ".git-credentials"
              - key: .gitconfig
                path: ".gitconfig"
            defaultMode: 0755
        - name: data
          emptyDir:
            sizeLimit: 1Gi
      restartPolicy: OnFailure
