# ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cloud-server-ingress-route
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`cloud-server-k8s.gpg123.vip`)
      kind: Rule
      services:
        - name: cloud-server-service
          port: 9099
  tls:
    certResolver: "myCertResolver"  # 引用 Let's Encrypt 解析器[9](@ref)