apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-server-ingress
spec:
  rules:
    - host: cloud-server-k8s.gpg123.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-server-service
                port:
                  number: 9099
                