server:
  port: 9097

spring:
  application:
    name: cloud-server-job
  profiles:
    active: druid,seata
  cloud:
    nacos:
      config:
        server-addr: 110.42.40.8:8848
        namespace: gaopuguang
        group: DEFAULT_GROUP
      discovery: #启用 spring cloud nacos discovery
        server-addr: 110.42.40.8:8848
        namespace: gaopuguang
        group: DEFAULT_GROUP