# 消息队列服务
spring:
  rabbitmq:
    port: 5672
    host: hcs.gpg123.vip
    username: admin
    password: admin
    #虚拟主机
    virtual-host: /
# 队列
queue:
  #邮件
  email: cloud-server-email
  # 短信
  sms: cloud-server-sms

  #5f6a7f047d97406dc0336692465d07ed