#分布式事务
seata:
  enabled: true
  application-id: cloud-server #添加为服务名
  tx-service-group: cloud-server-group  #事务组名称，要和服务端对应
  config:
    type: nacos
    nacos:
      namespace: seata-server
      server-addr: hcs.gpg123.vip:8848
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      namespace: seata-server
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
  service:
    vgroup-mapping:
      mygroup: default #key是事务组名称 value要和服务端的机房名称保持一致


